### ISSUE TITLE
Failure to install PE 2023

### ISSUE THREAD

**Issue by coreymbe** [jarretlavallee/puppet-deploy_pe#33]
Due to the change in PE 2023 of moving from Java 11 -> [Java 17](https://www.puppet.com/docs/pe/2023.0/release_notes_pe.html#release_notes_pe_x-0-enhancements-pe-x-0) the default settings now result in a failure to install the aforementioned PE version. In particular this is due to `pe.conf.epp` defaulting to include tuning and utilizes parameters no longer recognized in Java 17. In particular the following:

  * `MaxPermSize`
  * `PermSize`

```
out: Mar 21 23:15:04 systemd[1]: Starting pe-puppetserver Service...
out: Mar 21 23:15:04 puppetserver[4297]: Unrecognized VM option 'MaxPermSize=96m'
out: Mar 21 23:15:04 puppetserver[4297]: Error: Could not create the Java Virtual Machine.
out: Mar 21 23:15:04 puppetserver[4297]: Error: A fatal exception has occurred. Program will exit.
```

**Comment by jarretlavallee** [comment]
@coreymbe Thanks for opening this. Would you mind putting up a PR to remove these lines?
https://github.com/jarretlavallee/puppet-deploy_pe/blob/master/templates/pe.conf.epp#L39-L40

**Comment by jarretlavallee** [comment]
And these two as well
https://github.com/jarretlavallee/puppet-deploy_pe/blob/master/templates/pe.conf.epp#L32-L33

**Comment by coreymbe** [comment]
@jarretlavallee :: Can do 👍!

**Comment by coreymbe** [comment]
Resolved by https://github.com/jarretlavallee/puppet-deploy_pe/pull/34
